### ISSUE TITLE
docker error page

### ISSUE THREAD

**Issue by basicallynewbie** [drakonkat/webtorrent-express-api#13]
**Describe the bug**
I deployed it with docker-compose but get a blank page showing "error" when I visited it.I have tried latest and 1.7.4,they have the same result.

**To Reproduce**
1. docker-compose
```
version: "3.9"
services:
  crawfish:
    image: mauromazzocchetti/webtorrent-express-api:1.7.4
    container_name: crawfish
    volumes:
      - /home/me/docker/crawfish/downloads:/usr/src/app/Downloads
    ports:
      - 3015:3000
      - 51415:51415
    restart: unless-stopped
```
2. go to http://ip:3015 ,then showing "error"

**Expected behavior**
working normal

**Screenshots**
![error](https://user-images.githubusercontent.com/107107611/201138993-debcd825-7a86-4fa8-815a-38196d5f42f0.PNG)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser chrome
 - Version 107.0.5304.106

**Additional context**
logs:

```
> crawfish@1.7.4 prod
> node ./bin/www-prod

/bin/sh: 1: xdg-user-dir: not found
Starting the service... false true
Express server stared! Mode:  production
Error getting data at start:  Error [OpenError]: IO error: /root/Crawfish/config_db/LOCK: No such file or directory
    at /usr/src/app/node_modules/levelup/lib/levelup.js:119:23
    at /usr/src/app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /usr/src/app/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /usr/src/app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
Error reading file: /root/Crawfish/config.json
Error [OpenError]: IO error: /root/Crawfish/config_db/LOCK: No such file or directory
    at /usr/src/app/node_modules/levelup/lib/levelup.js:119:23
    at /usr/src/app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /usr/src/app/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /usr/src/app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14

node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^
Error [OpenError]: IO error: /root/Crawfish/config_db/LOCK: No such file or directory
    at /usr/src/app/node_modules/levelup/lib/levelup.js:119:23
    at /usr/src/app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14
    at /usr/src/app/node_modules/deferred-leveldown/deferred-leveldown.js:31:21
    at /usr/src/app/node_modules/abstract-leveldown/abstract-leveldown.js:38:14

> crawfish@1.7.4 prod
> node ./bin/www-prod

/bin/sh: 1: xdg-user-dir: not found
Starting the service... false true
Express server stared! Mode:  production
Error getting data at start:  Error
    at new CustomPouchError (/usr/src/app/node_modules/pouchdb/lib/index.js:656:21)
    at createError (/usr/src/app/node_modules/pouchdb/lib/index.js:665:10)
    at /usr/src/app/node_modules/pouchdb/lib/index.js:5183:25
    at /usr/src/app/node_modules/pouchdb/lib/index.js:4220:9
    at /usr/src/app/node_modules/pouchdb/lib/index.js:4051:13 {
  status: 404,
  name: 'not_found',
  message: 'missing',
  error: true,
  reason: 'missing',
  docId: 'configuration'
}
Error reading file: /root/Crawfish/config.json
Service started
Founded searx resource true
Error checking resource https://darmarit.org/searx/:  false

```

**Comment by drakonkat** [comment]
Hi, sorry for the late response can you try this path? "http://ip:3015/crawfish-official/index.html" and you can use an update versione of the repo. I changed name in crawfish even on docker, here is the latest [Official image](https://hub.docker.com/repository/docker/mauromazzocchetti/crawfish)

**Comment by basicallynewbie** [comment]
Thanks for reply. So there's a good news and a bad news. The bad news is the path still doesn't work with mauromazzocchetti/webtorrent-express-api. The good news is I can visit the webui in http://ip:3015/crawfish-official/index.html with mauromazzocchetti/crawfish but not http://ip:3015.

**Comment by drakonkat** [comment]
Yes actually to access it you need the path... after that i usually redirect it with nginx but can be a feature improvment to support the basic path "/"
